### ISSUE TITLE
lygadget ports compatible with SiEPIC

### ISSUE THREAD

**Issue by joamatab** [atait/klayout-gadgets#4]
I've been taking the edx course from Lukas and using your lygadgets to create a klayout library from a phidl library
https://github.com/gdsfactory/ubc

I tried adding an outline for device recognition (DEVREC) and PINS for all the ports, so I can use the auto-snapping and netlist extraction features that Lukas has. However I can't seem to be compatible with them, I suspect we need a zero-length Path for the pins.

![image](https://user-images.githubusercontent.com/4514346/92541205-31551900-f1fa-11ea-866a-3a86df29ab7d.png)

**Comment by joamatab** [comment]
Hi Alex, were you able to look at this?

**Comment by atait** [comment]
Hi @joamatab , sorry for the delay in looking into this feature. I have been between major layout projects, which are normally when I make changes to the libraries. This is on my todo!

**Comment by joamatab** [comment]
Thank you Alex, let me know how I could be of any help

**Comment by joamatab** [comment]
Do you have an example on how to define a Klayout compatible port? Im also happy to send a PR

**Comment by joamatab** [comment]
the fix is here 

the issue was with the label anchor

see add_pins_siepic here

https://github.com/gdsfactory/gdsfactory/blob/master/gdsfactory/add_pins.py
